ZUK_REPO_URLBASE_GITLAB = "git://gitlab.com/dreamchip"
ZUK_REPO_PROTOCOL_GITLAB = "https"
ZUK_REPO_URLBASE = "${ZUK_REPO_URLBASE_GITLAB}"
ZUK_REPO_PROTOCOL = "${ZUK_REPO_PROTOCOL_GITLAB}"

# ../../../recipes-kernel/dct-cpufreq/kernel-module-dct-cpufreq_1.0.bb
ZUK_REPO_NAME_CPUFREQ_GITLAB = "ip-sw-dct-cpufreq-driver"
ZUK_REPO_NAME_CPUFREQ = "${ZUK_REPO_NAME_CPUFREQ_GITLAB}"
ZUK_REPO_SRCREV_CPUFREQ = "v1-oss"
# ../../../recipes-kernel/dct-gpio/kernel-module-dct-gpio_1.0.bb
ZUK_REPO_NAME_GPIO_GITLAB = "ip-sw-dct-gpio-driver"
ZUK_REPO_NAME_GPIO = "${ZUK_REPO_NAME_GPIO_GITLAB}"
ZUK_REPO_SRCREV_GPIO = "v1-oss"
# ../../../recipes-kernel/dct-i2c/kernel-module-dct-i2c_1.0.bb
ZUK_REPO_NAME_I2C_GITLAB = "ip-sw-dct-i2c-driver"
ZUK_REPO_NAME_I2C = "${ZUK_REPO_NAME_I2C_GITLAB}"
ZUK_REPO_SRCREV_I2C = "v1-oss"
# ../../../recipes-kernel/dct-ipc/kernel-module-dct-ipc_1.0.bb
ZUK_REPO_NAME_IPC_GITLAB = "ip-sw-dct-ipc-driver"
ZUK_REPO_NAME_IPC = "${ZUK_REPO_NAME_IPC_GITLAB}"
ZUK_REPO_SRCREV_IPC = "v1-oss"
# ../../../recipes-kernel/dct-ipc-clk/kernel-module-dct-ipc-clk_1.0.bb
ZUK_REPO_NAME_IPC_CLK_GITLAB = "ip-sw-dct-ipc-clk-driver"
ZUK_REPO_NAME_IPC_CLK = "${ZUK_REPO_NAME_IPC_CLK_GITLAB}"
ZUK_REPO_SRCREV_IPC_CLK = "v1-oss"
# ../../../recipes-kernel/dct-ipc-gpio/kernel-module-dct-ipc-gpio_1.0.bb
ZUK_REPO_NAME_IPC_GPIO_GITLAB = "ip-sw-dct-ipc-gpio-driver"
ZUK_REPO_NAME_IPC_GPIO = "${ZUK_REPO_NAME_IPC_GPIO_GITLAB}"
ZUK_REPO_SRCREV_IPC_GPIO = "v1-oss"
# ../../../recipes-kernel/dct-irc5/kernel-module-dct-irc5_1.0.bb
ZUK_REPO_NAME_IRC5_GITLAB = "ip-sw-dct-irc5-driver"
ZUK_REPO_NAME_IRC5 = "${ZUK_REPO_NAME_IRC5_GITLAB}"
ZUK_REPO_SRCREV_IRC5 = "v1-oss"
# ../../../recipes-video/dct-isp-dma/kernel-module-dct-isp-dma_1.0.bb
ZUK_REPO_NAME_ISP_DMA_GITLAB = "ip-sw-dct-isp-dma-driver"
ZUK_REPO_NAME_ISP_DMA = "${ZUK_REPO_NAME_ISP_DMA_GITLAB}"
ZUK_REPO_SRCREV_ISP_DMA = "v1-oss"
# ../../../recipes-video/dct-isp-main/kernel-module-dct-isp-main_1.0.bb
ZUK_REPO_NAME_ISP_MAIN_GITLAB = "ip-sw-dct-isp-main-driver"
ZUK_REPO_NAME_ISP_MAIN = "${ZUK_REPO_NAME_ISP_MAIN_GITLAB}"
ZUK_REPO_SRCREV_ISP_MAIN = "v1-oss"
# ../../../recipes-video/dct-isp-pre/kernel-module-dct-isp-pre_1.0.bb
ZUK_REPO_NAME_ISP_PRE_GITLAB = "ip-sw-dct-isp-pre-driver"
ZUK_REPO_NAME_ISP_PRE = "${ZUK_REPO_NAME_ISP_PRE_GITLAB}"
ZUK_REPO_SRCREV_ISP_PRE = "v1-oss"
# ../../../recipes-video/dct-mvdu/kernel-module-dct-mvdu_1.0.bb
ZUK_REPO_NAME_MVDU_GITLAB = "ip-sw-dct-mvdu-driver"
ZUK_REPO_NAME_MVDU = "${ZUK_REPO_NAME_MVDU_GITLAB}"
ZUK_REPO_SRCREV_MVDU = "v1-oss"
# ../../../recipes-video/dct-nna/kernel-module-dct-nna_1.0.bb
ZUK_REPO_NAME_NNA_GITLAB = "ip-sw-dct-nna-driver"
ZUK_REPO_NAME_NNA = "${ZUK_REPO_NAME_NNA_GITLAB}"
ZUK_REPO_SRCREV_NNA = "v1-oss"
# ../../../recipes-kernel/dct-pcie/kernel-module-dct-pcie.bb
ZUK_REPO_NAME_PCIE_GITLAB = "ip-sw-dct-pcie-driver"
ZUK_REPO_NAME_PCIE = "${ZUK_REPO_NAME_PCIE_GITLAB}"
ZUK_REPO_SRCREV_PCIE = "v1-oss"
# ../../../recipes-kernel/dct-qspi/kernel-module-dct-qspi_1.0.bb
ZUK_REPO_NAME_QSPI_GITLAB = "ip-sw-dct-qspi-driver"
ZUK_REPO_NAME_QSPI = "${ZUK_REPO_NAME_QSPI_GITLAB}"
ZUK_REPO_SRCREV_QSPI = "v1-oss"
# ../../../recipes-kernel/dct-sdhci/kernel-module-dct-sdhci-cadence_1.0.bb
ZUK_REPO_NAME_SDHCI_CADENCE_GITLAB = "ip-sw-dct-sdhci-cadence-driver"
ZUK_REPO_NAME_SDHCI_CADENCE = "${ZUK_REPO_NAME_SDHCI_CADENCE_GITLAB}"
ZUK_REPO_SRCREV_SDHCI_CADENCE = "v1-oss"